use std::{fmt::Display, time::Instant};

/// Runs and emits both parts of an AOC day via provided closures, with timings.
pub fn solve<T: Display, F1: FnOnce() -> T, F2: FnOnce() -> T>(f1: F1, f2: F2) {
    let (r, d) = {
        let _tmr = Instant::now();
        (f1(), Instant::now().duration_since(_tmr))
    };
    println!("Part 1: {r} ({:?})", d);

    let (r, d) = {
        let _tmr = Instant::now();
        (f2(), Instant::now().duration_since(_tmr))
    };
    println!("Part 2: {r} ({:?})", d);
}

/// Fake unit struct used as part of the code generated by `cargo-day-template`.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct AnswerTbd;

impl Display for AnswerTbd {
    fn fmt(&self, _f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        unimplemented!();
    }
}
